version: "3"

services:
  zemoga-mobile-react-dev-test:
    platform: linux/amd64
    build: ./zemoga-mobile-react-dev-test
    ports:
      - "19000:19000"
      - "19006:19006"
      - "19001:19001"
      - "19002:19002"
    volumes:
      - ./zemoga-mobile-react-dev-test:/app
      - /app/node_modules
    networks:
      - zemoga_mobile_react_dev_test_net
    environment:
      - NODE_ENV=dev
      - EXPO_DEV_TOOLS_LISTEN=0.0.0.0
      - CI=true
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - REACT_NATIVE_PACKAGER_HOSTNAME=192.168.0.3 # If you need to build the app in an Android/iOS device, uncomment this variable and change the <IP> to your computer's IP and run 'docker-compose build'. For simulators/web it's not needed, as long as it is from the same computer running the project.
networks:
  zemoga_mobile_react_dev_test_net:
