version: "3"

services:
  zemoga-mobile-react-dev-test:
    build: ./zemoga-mobile-react-dev-test
    ports:
      - "19000:19000"
      - "19006:19006"
      - "19001:19001"
      - "19002:19002"
    volumes:
      - ./zemoga-mobile-react-dev-test:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - zemoga_mobile_react_dev_test_net
    environment:
      - NODE_ENV=dev
      - EXPO_DEV_TOOLS_LISTEN=0.0.0.0
      - CI=true
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - REACT_NATIVE_PACKAGER_HOSTNAME=192.168.0.3
      - WDS_SOCKET_HOST=127.0.0.1
networks:
  zemoga_mobile_react_dev_test_net:
  
